version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=${MYAPP_DATABASE}
      - POSTGRES_USERNAME=${MYAPP_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${MYAPP_DATABASE_PASSWORD}
      - POSTGRES_HOST=${MYAPP_DATABASE_HOST}
  web:
    build: .
    image: rails_template:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  js:
    image: rails_template:latest
    command: yarn build --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
  css:
    image: rails_template:latest
    command: yarn build:css --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
volumes:
  db:
  bundle:
  node_modules:
